-- MySQL Script generated by MySQL Workbench
-- Fri May  2 22:14:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoes` DEFAULT CHARACTER SET utf8 ;
USE `shoes` ;

-- -----------------------------------------------------
-- Table `shoes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoes`.`shoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`shoes` (
  `article` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `size` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`article`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoes`.`shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`shipment` (
  `tracker` INT NOT NULL AUTO_INCREMENT,
  `id` INT NOT NULL,
  `article` INT NOT NULL,
  `price` INT NOT NULL,
  `shipmentcol` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`tracker`),
  INDEX `user_idx` (`id` ASC) VISIBLE,
  INDEX `article_idx` (`article` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
